### ISSUE TITLE
The delegation name must exactly match the apex of the child zone

### ISSUE THREAD

**Issue by pawal** [CENTRccTLDs/TRTF#11]
Add requirements text.

**Comment by jschlyter** [comment]
RFC 1035 section 3.3.11 (?)

**Comment by pawal** [comment]
Not entirely sure what this means. Section 3.3.11 does not make it more clear to me.

**Comment by jschlyter** [comment]
No it doesn't, but I cannot find anything better.

**Comment by pawal** [comment]
I don't believe this is something that comes from Zonemaster. Perhaps @matsduf have an explanation?

**Comment by pawal** [comment]
https://github.com/dotse/zonemaster/blob/master/docs/specifications/tests/Delegation-TP/delegation06.md

**Comment by pawal** [comment]
The original requirement was to require the presence of the SOA record. These two requirements are not entirely the same.
