### ISSUE TITLE
One DS MUST match a least one DNSKEY in the child zone (per algorithm)

### ISSUE THREAD

**Issue by pawal** [CENTRccTLDs/TRTF#16]
Add test requirement.

**Comment by pawal** [comment]
DNSSEC02: https://github.com/dotse/zonemaster/blob/master/docs/specifications/tests/DNSSEC-TP/dnssec02.md

**Comment by jschlyter** [comment]
IMHO, this is a rather bad requirement prohibiting for cases where zone owner do not want to disclose a standby key. The real requirement should be that the there must exist at least one matching DNSKEY for each DS algorithm.

**Comment by pawal** [comment]
So the correct heading should be:

One DS MUST match a least one DNSKEY in the child zone

This is also be covered by another requirement that states that the at least one chain from DS to RRSIG must be complete.
