### ISSUE TITLE
The number of NSEC3 iterations must to be higher than what is allowed

### ISSUE THREAD

**Issue by pawal** [CENTRccTLDs/TRTF#17]
Add test requirement.

**Comment by jschlyter** [comment]
RFC 5155 section 10.3 specifies max number of iterations allowed.

**Comment by jschlyter** [comment]
Discuss/research sane values for non-RSA algorithms.

**Comment by jschlyter** [comment]
FWIW, both Unbound and BIND limited the number of iterations in their validator code based on public key size.

**Comment by pawal** [comment]
Do they have specific limitations for other key sizes than RSA also?

**Comment by jschlyter** [comment]
They work on "key size" only, so ECDSA P-256 is considered 256 bits in this context (thus limited to 150 iterations it seems)
