### ISSUE TITLE
All name servers must respond with the same SOA RNAME

### ISSUE THREAD

**Issue by pawal** [CENTRccTLDs/TRTF#3]
Add requirement text.

**Comment by jschlyter** [comment]
https://github.com/dotse/zonemaster/blob/master/docs/specifications/tests/Consistency-TP/consistency02.md

**Comment by pawal** [comment]
Do I understand the DISCUSS tag correctly is that we need a discussion on if this is a protocol requirement or not?

Is there a reason for having different RNAMEs in a multiple master scenario?

**Comment by jschlyter** [comment]
I'm not sure there is a good reason, but I cannot find a protocol requirement for RNAME to be consistent. We can just put a SHOULD here and be done with it.

**Comment by pawal** [comment]
Yes.
