### ISSUE TITLE
The SOA MNAME to have no illegal characters

### ISSUE THREAD

**Issue by pawal** [CENTRccTLDs/TRTF#32]
Add test requirement.

**Comment by jschlyter** [comment]
https://github.com/dotse/zonemaster/blob/master/docs/specifications/tests/Syntax-TP/syntax05.md (among others)

**Comment by jschlyter** [comment]
https://github.com/dotse/zonemaster/blob/master/docs/specifications/tests/Syntax-TP/syntax07.md
