### ISSUE TITLE
All name servers must respond with the same SOA parameters

### ISSUE THREAD

**Issue by pawal** [CENTRccTLDs/TRTF#4]
Add requirement text.

**Comment by jschlyter** [comment]
https://github.com/dotse/zonemaster/blob/master/docs/specifications/tests/Consistency-TP/consistency03.md

**Comment by pawal** [comment]
Since MNAME and RNAME is defined to be SOA parameters, and we just allowed those to differ protocol-wise, this makes this requirement more relaxed. However, there is one field that stands out from the RFC text, and this is the MINIMUM parameter.
