### ISSUE TITLE
SOA MNAME must not to point at a CNAME or DNAME alias

### ISSUE THREAD

**Issue by pawal** [CENTRccTLDs/TRTF#44]
Add test requirement.

**Comment by jschlyter** [comment]
ref: RFC2181 section 10.3

**Comment by jschlyter** [comment]
Is this a duplicate of #35 ?

**Comment by pawal** [comment]
I would say "same same but different". #35 says "FQDN" which just means a complete name (of a name server).

We can combine these by saying that it must resolve to A or AAAA.
