### ISSUE TITLE
MX record should be present in apex

### ISSUE THREAD

**Issue by pawal** [CENTRccTLDs/TRTF#46]
Add test requirement.

**Comment by jschlyter** [comment]
Do we really want to require domains to do email?

**Comment by pawal** [comment]
It is strongly recommended in section 7 of RFC 2142 that all domains should have a mailbox named hostmaster@domain.

For simplicity and regularity, it is strongly recommended that the well known mailbox name HOSTMASTER always be used HOSTMASTER@domain.
It is therefore necessary for any domain to publish an MX record. However, SMTP can make a delivery without the MX, using the A or AAAA record as specified in section 5.1 of RFC 5321.

https://github.com/dotse/zonemaster/blob/master/docs/specifications/tests/Zone-TP/zone09.md

**Comment by immon** [comment]
Nowadays many domains have RNAME from external domain - wordpress, squarespace, cloudflare, AWS, …
I did a quick test: out of top100 alexa names only 32% have RNAME in the same domain name.

I think MX check is unnecessary.

**Comment by jschlyter** [comment]
This is not related to SOA RNAME, this is related to MX of the apex.

**Comment by pawal** [comment]
This was closed by #47. Could still be two separate requirements though.
