### ISSUE TITLE
MX record in apex must point at an A or AAAA record

### ISSUE THREAD

**Issue by pawal** [CENTRccTLDs/TRTF#47]
Add test requirements.

**Comment by jschlyter** [comment]
_If_ there is an MX record in the apex, it should point to A/AAAA. Correct?
ref: RFC2181 section 10.3

**Comment by jschlyter** [comment]
Can we remove this and considered it replaced by #45 ?

**Comment by pawal** [comment]
Or vice versa, since the name must point to A or AAAA, no other types are allowed?

**Comment by pawal** [comment]
Well, both requirements are ok. They work in two parts:
1. The hostname must be a valid hostname
2. The hostname must resolve directly to A or AAAA

**Comment by pawal** [comment]
Could also of course be handled by one single requirement, since #45 is closed now. Or would we like them separate?

**Comment by jschlyter** [comment]
Single, positive, requires are better IMHO.

**Comment by pawal** [comment]
There is no section 10.3 in 2821.
