### ISSUE TITLE
SOA serial fuzziness revisited (section 5.1)

### ISSUE THREAD

**Issue by jschlyter** [CENTRccTLDs/TRTF#64]
From Ralf Weber:

There are use cases where the serial number rarely if ever is the same on all servers and it's only really used inside communication for a given domain and not during resolution. So the only people who know if a divergent serial number is a problem are the domain owners. So we shouldn't tell the public that this is a problem. I would say that a different SOA serial number could be seen as an indicator of an inconsistent setup, but that further analysis is required to really conclude that.

**Comment by pawal** [comment]
Doesn't the text already say this?

**Comment by jschlyter** [comment]
Yes, it does. Closing this issue.
