### ISSUE TITLE
The name servers must have distinct IP addresses

### ISSUE THREAD

**Issue by pawal** [CENTRccTLDs/TRTF#8]
Add requirements text.

**Comment by jschlyter** [comment]
https://github.com/dotse/zonemaster/blob/master/docs/specifications/tests/Delegation-TP/delegation02.md

Delegation to multiple name servers with the same IP address is most likely a typo OR a policy workaround. I propose this is a MUST.

**Comment by pawal** [comment]
I agree it is a MUST.

**Comment by pawal** [comment]
When writing the text I find it hard to argue for a MUST, when having two name servers is a SHOULD. We can change this to MUST later, writing SHOULD now.
