### ISSUE TITLE
The referral must fit into an non-truncated 512 byte UDP packet

### ISSUE THREAD

**Issue by pawal** [CENTRccTLDs/TRTF#9]
Add requirements text.

**Comment by jschlyter** [comment]
https://github.com/dotse/zonemaster/blob/master/docs/specifications/tests/Delegation-TP/delegation03.md.

Given that TCP is required, why is this a MUST?

**Comment by pawal** [comment]
I do not think we should have interdependencies between each requirement. Since most DNS traffic still is UDP-only, and the fact that there is still a lot of middleboxes (finally got to write that) that don't allow you to do DNS properly, I think this requirement still stands.

**Comment by pawal** [comment]
Given that RFC5625 exists, I will change this to SHOULD in the text.
